import Head from 'next/head'

import styles from '../styles/Home.module.css'
// import NavBar from ''
import Banner from 'components/banner/Banner'
// import Card from ''

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nextflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Nextflix</h1>
      {/* <NavBar /> */}
      <Banner
        title="Clifford the Big Red Dog"
        subtitle="a very cute dog"
        imgUrl="/static/clifford.webp"
      />
      {/* <Card /> */}
    </div>
  )
}
